### ISSUE TITLE
录制视频问题咨询

### ISSUE THREAD

**Issue by 13970821754** [SharryChoo/SAlbum#3]
录制视频的时候不能禁止拍照吗？

**Comment by SharryChoo** [comment]
意思是指仅录制吗？之前这个功能是仿照着微信做的，仅录制这个场景倒是被忽略了，后面会考虑添加一个开关控制的。

**Comment by 13970821754** [comment]
我们有个发布小视频的功能，发现有这个问题。如果录视频的时候可以拍照，那业务逻辑就有问题，最近有计划加上这个开关吗？

**Comment by SharryChoo** [comment]
嗯，刚刚在 1.0.2 中已经加入了，在 TakerConfig 中加入下面的代码就好了，感谢你的反馈
```
TakerConfig.Builder()
        ......
        // 是否仅支持视频录制
        .setJustVideoRecord(true)
        ......
```

**Comment by 13970821754** [comment]
现在只选择视频的时候，相册里面还会出现照片吗？

**Comment by 13970821754** [comment]
再提一个建议，增加一个cancel事件，点击导航栏返回按钮或者物理返回键的时候，触发cancel事件，目前你只是加了complete事件，返回的时候，没办法做逻辑处理。

**Comment by SharryChoo** [comment]
目前没有对视频做单独筛选的功能, 后面迭代的过程中会逐步完善, 谢谢你的反馈

**Comment by 13970821754** [comment]
可以让我把取消事件加上去吗?

**Comment by SharryChoo** [comment]
1.0.3-rc1 添加了未操作的回调,  方法名是一样的, 很抱歉这么晚才加上, 谢谢你的反馈
